version: "3"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - /apps/docker/sonarr/data:/config
      - /media/series:/tv #optional
      - /mnt:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - /apps/docker/radar:/config
      - /media/pelis:/movies #optional
      - /mnt:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    volumes:
      - /apps/docker/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Mexico_City
    devices:
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
      -
    volumes:
      - /apps/docker/jelly:/config
      - /apps/docker/jelly:/cache
      - type: bind
        source: /media
        target: /media
        read_only: true
    restart: unless-stopped
    
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Mexico_City
    ports:
      - 8191:8191
      - 8920:8920
      - 1900:1900
      - 7359:7359
    restart: unless-stopped 

  #portainer:
    #image: portainer/portainer-ce:latest
  #  ports:
   #   - 9443:9443
    #  volumes:
     #   - /apps/docker/portainer:/data
      #  - /var/run/docker.sock:/var/run/docker.sock
    #restart: unless-stopped
